### ISSUE TITLE
We should use unsigned_abs instead of std::abs

### ISSUE THREAD

**Issue by liangjs** [libtql/tqlib#16]
`std::abs(std::numeric_limits<T>::min())` is not defined.

In the following code, when `exponent` is the minimum negative integer in `T`, we will have undefined behavior.
https://github.com/libtql/tqlib/blob/f21d98a8ff583e12026477dd376f128429d74c42/number_theory/numeric.h#L73

**Comment by umutoztunc** [comment]
This is fixed with #15.
